create table coach_messages (
  id              bigint generated by default as identity primary key,
  conversation_id uuid not null,
  role            text not null check (role in ('user','assistant')),
  content         text not null,
  created_at      timestamptz not null default now()
);

alter table coach_messages enable row level security;

create policy coach_messages_select on coach_messages
  for select to anon, authenticated using (true);
create policy coach_messages_insert on coach_messages
  for insert to anon, authenticated with check (true);
